[package]
name = "cabbage-mmo"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
pumpkin = { path = "../../Pumpkin/pumpkin", default-features = false }
pumpkin-data = { path = "../../Pumpkin/pumpkin-data" }
pumpkin-nbt = { path = "../../Pumpkin/pumpkin-nbt" }
pumpkin-util = { path = "../../Pumpkin/pumpkin-util" }
pumpkin-world = { path = "../../Pumpkin/pumpkin-world" }
rusqlite = { version = "0.40.1", default-features = false, features = ["bundled"] }
ron = "0.12.2"
serde = { version = "1.0.229", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0.151", default-features = false, features = ["std"] }
futures = { version = "0.3.33", default-features = false, features = ["executor"] }
uuid = { version = "1.24.0", default-features = false, features = ["std", "v4"] }
rand = { version = "0.10.2", default-features = false, features = ["std", "std_rng", "thread_rng"] }
log = "0.4.33"

[dev-dependencies]
tokio = { version = "1.53.1", default-features = false, features = ["rt-multi-thread", "macros"] }
