[package]
name = "cabbage-mobai"
version = "0.1.0"
edition = "2024"

[dependencies]
pumpkin = { path = "../../Pumpkin/pumpkin" }
pumpkin-data = { path = "../../Pumpkin/pumpkin-data" }
pumpkin-util = { path = "../../Pumpkin/pumpkin-util" }
pumpkin-world = { path = "../../Pumpkin/pumpkin-world" }
rayon = "1.12"
flashmap = "0.2.0"
uuid = "1.23"
log = "0.4.33"
