[package]
name = "cabbage-mobai"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
cabbage-api = { path = "../api" }
pumpkin = { path = "../../Pumpkin/pumpkin", default-features = false }
pumpkin-data = { path = "../../Pumpkin/pumpkin-data" }
pumpkin-util = { path = "../../Pumpkin/pumpkin-util" }
pumpkin-world = { path = "../../Pumpkin/pumpkin-world" }
rayon = { version = "1.12.0", default-features = false }
flashmap = "0.2.0"
uuid = { version = "1.24.0", default-features = false, features = ["std", "v4"] }
log = "0.4.33"
